{
 "title": "My Dashboard Title",
 "description": "dbmonitor output stored in influx importing dbmonitor outputs",
 "time": { "from": "2024-12-06T12:21:57.065Z", "to": "2024-12-06T13:54:46.460Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "customer_name",
    "label": "Customer",
    "query": {
     "query": "select distinct(customer) from customer_server"
    }
   },
   {
    "name": "Machine",
    "label": "machine_name",
    "query": {
     "query": "select distinct(machine) from customer_server WHERE customer =~ /^$customer_name$/"
    }
   },
   { "name": "page_size", "label": "Page Size", "query": "2.0,4.0,8.0,12.0,16.0" },
   {
    "name": "profile_type",
    "label": "Page Size",
    "query": "bfrd,bfwrt,dlks,isdel,isrd,isrwt,iswrt,lkrqs,lkwts,nextns,npages,npdata,nrows,nused,seqsc"
   },
   {
    "name": "Partitions",
    "label": "partition_name",
    "query": "SELECT tag_1,top(buffer_reads,tag_1,20) FROM (SELECT sum($profile_type) as buffer_reads  FROM partition_summary WHERE \"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/ AND $timeFilter GROUP BY tag_1)"
   }
  ]
 },
 "panels": [
  { "title": "Partition Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Partitions" },
  {
   "title": "Partition $profile_type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "repeat": "profile_type",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "metric::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "partition_summary",
     "select": [
      [
       { "params": [ "$profile_type" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "$profile_type", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU and bets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "cpu_avg_busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "osmon_sum",
     "query": "SELECT max(\"cpu_avg_busy\") FROM \"osmon_sum\" WHERE (\"customer\"::tag =~ /^$customer_name$/ AND \"server\"::tag =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "cpu_avg_busy" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    },
    {
     "alias": "bets_per_minute",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bets_per_min",
     "query": "SELECT sum(\"bpm\") FROM \"bets_per_min\" WHERE (\"customer\"::tag =~ /^$customer_name$/ AND \"server\"::tag =~ /^$Machine$/) AND $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "bpm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "customer", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "machine", "operator": "=~", "value": "/^$Machine$/" }
     ]
    },
    {
     "alias": "cpu_avg_busy_1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "osmon_sum",
     "query": "SELECT max(\"cpu_avg_busy\") FROM \"osmon\"WHERE (\"customer\"::tag =~ /^$customer_name$/ AND \"server\"::tag =~ /^$Machine$/) AND $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "cpu_avg_busy" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  { "title": "CPU ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "db_check_info",
     "select": [
      [
       { "params": [ "text" ], "type": "field" },
       { "params": [ "text" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU use by App/Server (%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu_by_app",
     "query": "SELECT max(\"cores\") FROM \"default\".\"server_usage\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/) AND metric !~/TOTAL/ AND $timeFilter GROUP BY time($__interval), \"tag_1\" fill(none)",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" },
      { "condition": "AND", "key": "metric::tag", "operator": "!=", "value": "TOTAL" }
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"cpu_avg_busy\") FROM \"default\".\"osmon\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU use by App/Server (cores)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu_by_app",
     "query": "SELECT max(\"cores\") FROM \"default\".\"server_usage\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/) AND metric !~/TOTAL/ AND $timeFilter GROUP BY time($__interval), \"tag_1\" fill(none)",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" },
      { "condition": "AND", "key": "metric::tag", "operator": "!=", "value": "TOTAL" }
     ]
    }
   ]
  },
  { "title": "Queues and General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 1, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "onstat-g_ntu",
     "select": [
      [
       { "params": [ "connects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "onstat-u",
     "select": [
      [
       { "params": [ "buffer_waits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "checkpoint_waits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "checkpoint" ], "type": "alias" }
      ],
      [
       { "params": [ "trans_cleanup" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "trans_cleanup" ], "type": "alias" }
      ],
      [
       { "params": [ "lock_waits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "locks" ], "type": "alias" }
      ],
      [
       { "params": [ "mutex_waits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "mutexes" ], "type": "alias" }
      ],
      [
       { "params": [ "write_to_logical_log" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "logical_log_writes" ], "type": "alias" }
      ],
      [
       { "params": [ "transaction_waits" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "transactions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "queues summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "queues_summary",
     "query": "SELECT max(\"mtx_avg\") AS \"mutex average\", max(\"rea_avg\") AS \"ready queue average\", max(\"rea_rep_pct\") AS \"repeating query average\", max(\"act_avg\") AS \"active average\", max(\"lck_mtx_avg\") AS \"locked mutex average\" FROM \"default\".\"queue_summary\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/  ) AND $timeFilter AND lck_mtx_avg < 3000 GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "mtx_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "mutex average" ], "type": "alias" }
      ],
      [
       { "params": [ "rea_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "ready queue average" ], "type": "alias" }
      ],
      [
       { "params": [ "rea_rep_pct" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "repeating query average" ], "type": "alias" }
      ],
      [
       { "params": [ "act_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "active average" ], "type": "alias" }
      ],
      [
       { "params": [ "lck_mtx_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "locked mutex average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_tag_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag_1" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"backlog\") FROM \"default\".\"replication_info\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/) AND $timeFilter GROUP BY time($__interval),tag_1 fill(linear)",
     "select": [
      [
       { "params": [ "backlog" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "VP cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "vpcache",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vpcache",
     "select": [
      [
       { "params": [ "sizeMB" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "onstat-g_seg",
     "select": [
      [
       { "params": [ "pctused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% used" ], "type": "alias" }
      ],
      [
       { "params": [ "segs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "segments" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "informix total locks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "total_locks",
     "select": [
      [
       { "params": [ "total_locks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "procedure cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "onstat-g_prc",
     "select": [
      [
       { "params": [ "ref_cnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ref_cnt" ], "type": "alias" }
      ],
      [
       { "params": [ "entriesinuse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "entries in use" ], "type": "alias" }
      ],
      [
       { "params": [ "dropped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "dropped" ], "type": "alias" }
      ],
      [
       { "params": [ "numlists" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "number of lists" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": " Checkpoint Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "checkpoints",
     "select": [
      [
       { "params": [ "block_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "time blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "cp_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "checkpoint time" ], "type": "alias" }
      ],
      [
       { "params": [ "longest_crit_wait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "lonest critical wait" ], "type": "alias" }
      ],
      [
       { "params": [ "tot_crit_wait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "total critical wait" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "flush time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": " Checkpoint Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "checkpoints",
     "select": [
      [
       { "params": [ "dskflush_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "disk flushes per second" ], "type": "alias" }
      ],
      [
       { "params": [ "n_dirty_buffs" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "dirty buffers" ], "type": "alias" }
      ],
      [
       { "params": [ "llogs_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "logical logs pages per second" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Disk statistics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "osmon_sum",
     "select": [
      [
       { "params": [ "await_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "average wait" ], "type": "alias" }
      ],
      [
       { "params": [ "await_hotavg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "hot disk average" ], "type": "alias" }
      ],
      [
       { "params": [ "await_hotcnt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "hot disk count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "osmon_sum",
     "select": [
      [
       { "params": [ "svctm_hotavg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "service time hot average" ], "type": "alias" }
      ],
      [
       { "params": [ "pctutil_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "percentage utilization average" ], "type": "alias" }
      ],
      [
       { "params": [ "svctm_hotcnt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "service time hot count" ], "type": "alias" }
      ],
      [
       { "params": [ "pctutil_hotavg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "percent utilization average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  {
   "title": "informix network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "onstat-g_ntu",
     "select": [
      [
       { "params": [ "connects" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "connects" ], "type": "alias" }
      ],
      [
       { "params": [ "total_reads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "total reads" ], "type": "alias" }
      ],
      [
       { "params": [ "total_writes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "total writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }, "repeat": "page_size" },
  {
   "title": "$page_size k buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "buffer_k",
     "query": "SELECT difference(mean(\"bufreads\")) AS \"buff reads\", difference(mean(\"bufwrits\")) AS \"buff writes\", difference(mean(\"bufwaits\")) AS \"buff waits\", mean(\"bufwrits_sinceckpt\") AS \"buff writes since checkpoint\" FROM \"default\".\"buffers\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/ AND \"tag_1\" =~ /^$page_size$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bufreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "buff reads" ], "type": "alias" }
      ],
      [
       { "params": [ "bufwrits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "buff writes" ], "type": "alias" }
      ],
      [
       { "params": [ "bufwaits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "buff waits" ], "type": "alias" }
      ],
      [
       { "params": [ "bufwrits_sinceckpt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buff writes  since CP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" },
      { "condition": "AND", "key": "pagesize::tag", "operator": "=~", "value": "/^$page_size$/" }
     ]
    }
   ]
  },
  {
   "title": "$page_size k buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "buffer_k",
     "query": "SELECT difference(mean(\"bufreads\")) AS \"buff reads\" FROM \"default\".\"buffers\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/ AND \"tag_1\" = 'select tag value') AND $timeFilter GROUP BY time($__interval), \"tag_1\" fill(none)",
     "select": [
      [
       { "params": [ "dskreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "disk reads" ], "type": "alias" }
      ],
      [
       { "params": [ "dskwrits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "disk writes" ], "type": "alias" }
      ],
      [
       { "params": [ "pagreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "page reads" ], "type": "alias" }
      ],
      [
       { "params": [ "pagwrits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "page writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" },
      { "condition": "AND", "key": "pagesize::tag", "operator": "=~", "value": "/^$page_size$/" }
     ]
    }
   ]
  },
  {
   "title": "$page_size k buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "buffer_k",
     "query": "SELECT difference(mean(\"bufreads\")) AS \"buff reads\" FROM \"default\".\"buffers\" WHERE (\"customer\" =~ /^$customer_name$/ AND \"machine\" =~ /^$Machine$/ AND \"tag_1\" = 'select tag value') AND $timeFilter GROUP BY time($__interval), \"tag_1\" fill(none)",
     "select": [
      [
       { "params": [ "Chunk_Writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "chunk writes" ], "type": "alias" }
      ],
      [
       { "params": [ "Fg_Writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "fg writes" ], "type": "alias" }
      ],
      [
       { "params": [ "LRU_Writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "LRU writes" ], "type": "alias" }
      ],
      [
       { "params": [ "flushes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "flushes" ], "type": "alias" }
      ],
      [
       { "params": [ "per_read_cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read cache" ], "type": "alias" }
      ],
      [
       { "params": [ "per_writecached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write cache" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" },
      { "condition": "AND", "key": "pagesize::tag", "operator": "=~", "value": "/^$page_size$/" }
     ]
    }
   ]
  },
  { "title": "Buffer Fast Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "Fast Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "buffer_fast",
     "select": [
      [
       { "params": [ "gets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "gets" ], "type": "alias" }
      ],
      [
       { "params": [ "hits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "hits" ], "type": "alias" }
      ],
      [
       { "params": [ "puts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "puts" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_hits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% hits" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  },
  { "title": "LRUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 }, "repeat": "page_size" },
  {
   "title": "$page_size  k LRU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 217 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lru_k",
     "query": "SELECT mean(\"dirtypctnow\") FROM \"default\".\"lru_stats\" WHERE (\"tag_1\" =~ /^$page_size$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dirtypctnow" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "dirty percent" ], "type": "alias" }
      ],
      [
       { "params": [ "tgtpctdirty" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "target dirty" ], "type": "alias" }
      ],
      [
       { "params": [ "stopflushGB" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "stop flushing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pagesize::tag", "operator": "=~", "value": "/^$page_size$/" },
      { "condition": "AND", "key": "customer::tag", "operator": "=~", "value": "/^$customer_name$/" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$Machine$/" }
     ]
    }
   ]
  }
 ]
}